from tournament.models.activity import *
from tournament.models.competitor import *
from tournament.models.contest import *
from tournament.models.event import *
from tournament.models.grade import *
from tournament.models.general import *
from tournament.models.round import *
from tournament.models.score import *
from tournament.models.tournament import *