# Generated by Django 2.2.4 on 2019-09-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190901_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullname',
            old_name='preferred_firstname',
            new_name='preferred_name',
        ),
    ]
