# Generated by Django 2.2.4 on 2019-09-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190901_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullname',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='fullname',
            name='middlenames',
            field=models.CharField(blank=True, max_length=50, verbose_name='Middle Name/s'),
        ),
        migrations.AlterField(
            model_name='fullname',
            name='preferred_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Preferred Name'),
        ),
    ]
