# Generated by Django 2.2.4 on 2019-09-05 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190904_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personname',
            name='birth_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_name', to='user.FullName'),
        ),
    ]
