# Generated by Django 2.2.4 on 2019-09-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='temp_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
