# Generated by Django 2.2.4 on 2019-09-15 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190909_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('middlenames', models.CharField(blank=True, max_length=50, verbose_name='Middle Name/s')),
                ('surname', models.CharField(max_length=30)),
                ('preferred_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Preferred Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='persongender',
            name='birth_gender',
        ),
        migrations.RemoveField(
            model_name='persongender',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personname',
            name='birth_name',
        ),
        migrations.RemoveField(
            model_name='personname',
            name='name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='person',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_user_birth', to='user.Gender'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_user', to='user.Gender'),
        ),
        migrations.DeleteModel(
            name='FullName',
        ),
        migrations.DeleteModel(
            name='GPS',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PersonGender',
        ),
        migrations.DeleteModel(
            name='PersonName',
        ),
        migrations.AddField(
            model_name='name',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='name',
            name='user_birth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
