# Generated by Django 2.2.4 on 2019-09-17 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190917_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='name',
            name='user',
        ),
        migrations.AddField(
            model_name='name',
            name='user_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='name',
            name='user_birth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birth_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='ContactDetails',
        ),
    ]
