# Generated by Django 2.2.4 on 2019-10-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20190925_0842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='CustomUserName',
        ),
        migrations.RenameModel(
            old_name='Signup',
            new_name='UserSignup',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_authorised',
            field=models.BooleanField(default=False),
        ),
    ]
