# Generated by Django 2.2.4 on 2019-10-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20191009_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birth_gender',
        ),
        migrations.RemoveField(
            model_name='customusername',
            name='user_birth',
        ),
    ]
