# Generated by Django 2.2.4 on 2019-09-21 07:18

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0017_auto_20190917_1319'),
        ('hub', '0005_auto_20190921_1914'),
        ('tournament', '0002_auto_20190921_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_team', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_hub', models.BooleanField(default=False)),
                ('is_hub_group', models.BooleanField(default=False)),
                ('colour', colorful.fields.RGBColorField()),
                ('text_colour', colorful.fields.RGBColorField(colors=['#000000', '#ffffff'])),
                ('hub_groups', models.ManyToManyField(related_name='competitor_groups', to='hub.HubGroup')),
                ('hubs', models.ManyToManyField(related_name='competitor_groups', to='hub.Hub')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitorGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('competitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant', to='tournament.Competitor')),
                ('custom_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_participations', to=settings.AUTH_USER_MODEL)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Gender')),
                ('hub_groups', models.ManyToManyField(related_name='participants', to='hub.HubGroup')),
                ('ranks', models.ManyToManyField(to='tournament.Rank')),
            ],
        ),
        migrations.AlterField(
            model_name='contest',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'pk__in': ()}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='TournamentCompetitorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='tournament.CompetitorGroup')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_groups', to='tournament.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('middlenames', models.CharField(blank=True, max_length=50, verbose_name='Middle Name/s')),
                ('surname', models.CharField(max_length=30)),
                ('preferred_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Preferred Name')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='tournament.Participant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='competitorgroup',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_groups', to='tournament.CompetitorGroupType'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='competitor_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitors', to='tournament.TournamentCompetitorGroup'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='participants',
            field=models.ManyToManyField(related_name='competitor_teams', to='tournament.Participant'),
        ),
    ]
