# Generated by Django 2.2.4 on 2019-09-24 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0006_auto_20190925_0842'),
        ('user', '0018_auto_20190925_0842'),
        ('tournament', '0007_auto_20190923_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('middlenames', models.CharField(blank=True, max_length=50, verbose_name='Middle Name/s')),
                ('surname', models.CharField(max_length=30)),
                ('preferred_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Preferred Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='participantname',
            name='participant',
        ),
        migrations.RenameField(
            model_name='competitor',
            old_name='name',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='sub_activities',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='participants',
        ),
        migrations.AddField(
            model_name='activity',
            name='super_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_activities', to='tournament.Activity'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='competitors',
            field=models.ManyToManyField(related_name='_competitor_competitors_+', to='tournament.Competitor'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='custom_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competitor',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitor',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Gender'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='hub_groups',
            field=models.ManyToManyField(related_name='competitors', to='hub.HubGroup'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='hub_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_tournaments', to='hub.HubMember'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='ranks',
            field=models.ManyToManyField(to='tournament.Rank'),
        ),
        migrations.AddField(
            model_name='competitorgroup',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='competitorgrouptype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'pk__in': ()}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='contestinstance',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'pk__in': ()}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='measurementunitgroup',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='roundsystem',
            name='content_type',
            field=models.ForeignKey(default='', limit_choices_to={'pk__in': ()}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'pk__in': ()}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='created_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='ParticipantName',
        ),
        migrations.AddField(
            model_name='competitorname',
            name='competitor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='tournament.Competitor'),
        ),
    ]
