# Generated by Django 2.2.4 on 2019-09-17 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20190915_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hub',
            name='type',
        ),
        migrations.AddField(
            model_name='hub',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hub',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='HubAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=50, verbose_name='Address Line 1')),
                ('line2', models.CharField(blank=True, max_length=50, verbose_name='Address Line 2')),
                ('line3', models.CharField(blank=True, max_length=50, verbose_name='Address Line 3')),
                ('town_city', models.CharField(max_length=50, verbose_name='Town/City')),
                ('postcode', models.CharField(blank=True, max_length=50, verbose_name='Postcode')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('hub', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='hub.Hub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hub',
            name='hub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.HubType'),
        ),
    ]
