# Generated by Django 2.2.4 on 2019-09-19 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20190917_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='main_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_main_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
