# Generated by Django 2.2.4 on 2019-09-21 07:14

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20190919_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hub',
            name='permission_admin',
            field=models.ManyToManyField(related_name='hub_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hub',
            name='permission_staff',
            field=models.ManyToManyField(related_name='hub_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('colour', colorful.fields.RGBColorField(blank=True)),
                ('text_colour', colorful.fields.RGBColorField(blank=True, colors=['#000000', '#ffffff'])),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_groups', to='hub.Hub')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_groups', to='hub.HubGroupType')),
            ],
        ),
    ]
