# Generated by Django 2.2.4 on 2019-09-24 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20190923_2214'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0018_auto_20190925_0842'),
        ('hub', '0005_auto_20190921_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsn', models.CharField(blank=True, max_length=30)),
                ('dob', models.DateField(null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='HubMembershipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hub',
            name='permission_staff',
        ),
        migrations.AddField(
            model_name='hubgroup',
            name='auto_end_membership',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hubgroup',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hubgroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hubgroup',
            name='start_date',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hubgroup',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='RankHubMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_end_membership', models.DateField(null=True, blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='hub.HubMember')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Rank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_end_membership', models.DateField(blank=True, null=True)),
                ('membership_id', models.CharField(blank=True, max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hub.HubMember')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.HubMembershipType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubMemberName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='First Name')),
                ('middlenames', models.CharField(blank=True, max_length=50, verbose_name='Middle Name/s')),
                ('surname', models.CharField(max_length=30)),
                ('preferred_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Preferred Name')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='hub.HubMember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HubMemberAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=50, verbose_name='Address Line 1')),
                ('line2', models.CharField(blank=True, max_length=50, verbose_name='Address Line 2')),
                ('line3', models.CharField(blank=True, max_length=50, verbose_name='Address Line 3')),
                ('town_city', models.CharField(max_length=50, verbose_name='Town/City')),
                ('postcode', models.CharField(blank=True, max_length=50, verbose_name='Postcode')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Country')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='hub.HubMember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hubmember',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='hub.Hub'),
        ),
        migrations.AddField(
            model_name='hubmember',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HubGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_end_membership', models.DateField(blank=True, null=True)),
                ('hub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.HubGroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_groups', to='hub.HubMember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
