# Generated by Django 2.2.4 on 2019-09-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0006_auto_20190925_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubgroup',
            name='auto_end_membership',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubgroup',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubgroup',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hubgroupmembership',
            name='auto_end_membership',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubgroupmembership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubgroupmembership',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hubmember',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hubmembership',
            name='auto_end_membership',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubmembership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hubmembership',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rankhubmembership',
            name='auto_end_membership',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankhubmembership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankhubmembership',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
