# Generated by Django 2.2.4 on 2019-09-26 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hub', '0007_auto_20190925_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubmembershiptype',
            name='hub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_membership_types', to='hub.HubType'),
        ),
        migrations.CreateModel(
            name='HubSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Hub Name')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Hub Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Hub Email')),
                ('town_city', models.CharField(max_length=30, verbose_name='Town/City')),
                ('hub_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.HubType', verbose_name='Hub Type')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
