# Generated by Django 2.2.4 on 2019-10-09 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tournament', '0015_auto_20191009_1701'),
        ('hub', '0008_auto_20190926_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubRoleLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HubRoleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_id_number', models.CharField(blank=True, max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hub.HubMember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MembershipPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.RemoveField(
            model_name='hubgroup',
            name='auto_end_membership',
        ),
        migrations.RemoveField(
            model_name='hubgroup',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hubgroupmembership',
            name='auto_end_membership',
        ),
        migrations.RemoveField(
            model_name='hubgroupmembership',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='hubgroupmembership',
            name='hub_group',
        ),
        migrations.RemoveField(
            model_name='hubgroupmembership',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hubgroupmembership',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='rankhubmembership',
            name='auto_end_membership',
        ),
        migrations.RemoveField(
            model_name='rankhubmembership',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='rankhubmembership',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='rankhubmembership',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='rankhubmembership',
            name='start_date',
        ),
        migrations.AddField(
            model_name='hubgroupmembership',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_memberships', to='hub.HubGroup'),
        ),
        migrations.AddField(
            model_name='hubgroupmembership',
            name='membership_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rankhubmembership',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hub_rank_memberships', to='tournament.Rank'),
        ),
        migrations.AddField(
            model_name='rankhubmembership',
            name='membership_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='hubgroup',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hubgroupmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hub.HubMember'),
        ),
        migrations.AlterField(
            model_name='rankhubmembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='hub.HubMember'),
        ),
        migrations.RenameModel(
            old_name='HubMembershipType',
            new_name='HubRole',
        ),
        migrations.DeleteModel(
            name='HubMembership',
        ),
        migrations.AddField(
            model_name='hubrolemembership',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_memberships', to='hub.HubRole'),
        ),
    ]
