# Generated by Django 2.2.4 on 2019-10-18 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_auto_20191009_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubmember',
            name='nsn',
        ),
        migrations.AlterField(
            model_name='hub',
            name='hub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hub.HubType', verbose_name='Hub Type'),
        ),
    ]
