# Generated by Django 2.2.4 on 2019-10-18 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20191018_1745'),
        ('hub', '0010_auto_20191018_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubmember',
            name='nsn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hub_members', to='user.NSN'),
        ),
    ]
